### ISSUE TITLE
missing tag propagators/opencensus/v1.0.0

### ISSUE THREAD

**Issue by errordeveloper** [open-telemetry/opentelemetry-go-contrib#1357]
Looks like this [tag](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/propagators/opencensus%2Fv1.0.0) hasn't been set.

**Comment by MrAlias** [comment]
This seems intentional as that package is not included in the `v1.0.0` module set:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/b72c2cd63b9a9917554cbcd709e61f5d8541eea5/versions.yaml#L32

I'm not entirely sure why this was omitted from the release though. @Aneurysm9 might have more context here.

**Comment by Aneurysm9** [comment]
It [depends on the OpenCensus bridge module](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/opencensus/go.mod#L9), which isn't 1.0 because it depends on metrics.
