### ISSUE TITLE
otelgrpc and grpc.ChainInterceptors (multiple tracerProviders)

### ISSUE THREAD

**Issue by nexcode** [open-telemetry/opentelemetry-go-contrib#1548]
**instrumentation**: `google.golang.org/grpc/otelgrpc`

I want to use multiple `tracerProvider` to collect traces in different systems. For example: Zipkin and Jaeger.

For this we need to use interceptor chains (for server and client respectively):
```go
grpc.WithChainUnaryInterceptor(otelgrpc.UnaryClientInterceptor(tracerProviderZipkin, propagators))
grpc.WithChainStreamInterceptor(otelgrpc.StreamClientInterceptor(tracerProviderZipkin, propagators))

grpc.WithChainUnaryInterceptor(otelgrpc.UnaryClientInterceptor(tracerProviderJaeger, propagators))
grpc.WithChainStreamInterceptor(otelgrpc.StreamClientInterceptor(tracerProviderJaeger, propagators))
```

In general, statistics are collected on two systems, but the **last system** (Jaeger) has a bug with tree formation: https://github.com/jaegertracing/spark-dependencies/issues/111 (**all spans are at the first nesting level**)

**Comment by Aneurysm9** [comment]
I don't think you want to do this by adding multiple interceptors as that will create multiple spans that are only partially exported to each system.  Instead, I think adding multiple exporters to your `TracerProvider` is the approach to take.  Then there would be a singe interceptor and all spans would be sent to all destinations.  It should be possible to just add another `WithBatcher(zipkinExporter)` to the `TracerProvider` initializer.

**Comment by nexcode** [comment]
Yes, you can put several `SpanProcessors` in `TraceProvider`. But then it will not work to set up different **Sampling** or differently collected **Resource** objects per exporter. These settings are common for the `TraceProvider`.

```go
tracerProvider := otelgrpc.WithTracerProvider(trace.NewTracerProvider(
  trace.WithBatcher(exporter1),
  trace.WithBatcher(exporter2),
  trace.WithSampler(...),
  trace.WithResource(...),
))
```

Is there any way to configure this separately for the exporter?

**Comment by Aneurysm9** [comment]
I don't believe that is possible and it's not clear to me that it would be desirable.  Can you elaborate on your use case?

The resource should identify the workload that is producing the telemetry and should not vary depending on where the telemetry is sent.  If there is sensitive information in the resource that cannot be sent to a destination then it may be possible to wrap the batch span processor for that destination in a span processor that clones the trace data and redacts information from the resource.  Otherwise, the collector could be interposed as a single destination and configured with separate pipelines for each downstream destination with resource attribute modification on one or more pipelines.

Different head sampling results cannot be achieved within the SDK as there is a single point of truth for whether a span has been sampled in the `SpanContext`.  Tail sampling with a span processor may be possible, but would risk breaking traces by failing to export some spans.  Tail sampling in a collector configured to ensure that it can operate on entire traces is the safest approach.
