### ISSUE TITLE
Getting Cortex dependencies errors

### ISSUE THREAD

**Issue by ShiranAvidov** [open-telemetry/opentelemetry-go-contrib#1638]
I am running this command:
go get -u go.opentelemetry.io/contrib/exporters/metric/cortex 
and gets the errors:
../../go/pkg/mod/go.opentelemetry.io/contrib/exporters/metric/cortex@v0.27.0/cortex.go:163:35: undefined: aggregation.MinMaxSumCount
../../go/pkg/mod/go.opentelemetry.io/contrib/exporters/metric/cortex@v0.27.0/cortex.go:242:65: undefined: aggregation.MinMaxSumCount

If I understand correctly MinMaxSumCount no longer exists in the latest version (v0.27.0).

**Comment by Aneurysm9** [comment]
Correct, that aggregation type was removed in the latest metrics SDK release.  We have not yet released a version of the Cortex exporter that works without it, though it has been fixed on HEAD.  You may be able to use the pseudo-version `main` for the cortex exporter module in your `go.mod` file, otherwise we are planning to make a release this week that will include that fix.
