### ISSUE TITLE
Can OpenTelemetry SDK used for go language operator deployed in AKS cluster.

### ISSUE THREAD

**Issue by sakanwar** [open-telemetry/opentelemetry-go-contrib#3187]
Hi Team,

Reaching out to you for help needed for AKS logging. We have written one operator in Go language and looking for logging and monitoring of that operator. The official documentation of OpenTelemetry says that logs and metric is still in preview for go language. Can Opentelemetry is reliable enough to be used for logging and monitoring? Any suggestion from your side?
https://opentelemetry.io/docs/instrumentation/#status-and-releases

 Thanks in advance.

**Comment by dmathieu** [comment]
Hi,

The Go SDK has no implementation for logs at all at the moment. So no, you cannot use the SDK for that. The [collector](https://opentelemetry.io/docs/collector/) can receive logs and transfer them elsewhere though.
Metrics are currently in beta, so yes, they are available.

As for being reliable, several companies are currently using it in production. But you should be conducting your own tests if you wish to.

Since this ticket isn't about an actual issue, I'm closing it. Feel free to ask further questions though.
