### ISSUE TITLE
MongoDB Driver creates new traces in Jaeger instead of adding to existing trace

### ISSUE THREAD

**Issue by ChrisJBurns** [open-telemetry/opentelemetry-go-contrib#319]
Hi,

So I'm writing a blog post about OpenTelemetry and I am more specifically writing up about Tracing. I'm setting up a few microservices to show the power of tracing with Jaeger as the main UI to see the traces. However during the Golang development of the service I am having problems.

Currently I've got a basic service that creates employees and gets employees and am doing so via the gin-tonic library that is in this repo. This is working fine so far, I'm able to create multiple spans under the same trace using the Context. However, when I make a MongoDB call I am seeing that with the `clientOptions.Monitor = mongotrace.NewMonitor("jaeger-tracing-go-service")` option that is in the example of the mongodb-driver package, I can see that in Jaeger it is creating a brand new trace instead of a span within a trace. Is this correct? I ask because the information that is sent to Jaeger for the trace is very helpful however it always comes under its own trace instead of being a span within an overall trace. Is there a way I can tell it to stay within the same tracing context?

Sorry if I've got the wrong end of the stick, still learning this and Golang isn't my first language either.

**Comment by evantorrie** [comment]
Are you passing the `*gin.Context.Request.Context` object from the gin-tonic handler to the requisite `mongo.Client` operations?

It may be a little confusing with `gin-gonic/gin` because it has its own type `gin.Context` which gets passed as a parameter to an HTTP handler. But the context which should be passed down into the mongo.Client operations is the standard Go library `Context` object, available in `gin.Context.Request.Context`.  

It is this `Context` that should be passed to such mongodb operations as `Connect(ctx, ...)`, `InsertOne(ctx, ...)`, etc.

**Comment by ChrisJBurns** [comment]
@evantorrie That's great, thank you so much. I remember playing around with the `Context` object yesterday quite a lot and couldn't get it to work. So it seems I was using the incorrect `Context` Object. Thank you :)

Is this worth adding to the documentation or is this something I missed from some documentation somewhere?

**Comment by evantorrie** [comment]
In Go, the concept of the built-in `context.Context` in the standard library is fairly well understood and almost universal these days, but it was not introduced into Go until version 1.7. I imagine that `gin-gonic`'s `Context` predates this standard library availability, which is why there's the conflict in names.

The [example code](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/faaf7c0468c2094b8d2b7f4d795375a4c43d8f2b/instrumentation/github.com/gin-gonic/gin/example/server.go#L45) in this repo does show that you need to pass gin's `Context.Request.Context()` to OpenTelemetry tracers, but perhaps a single comment in there to remind users of the difference between `gin.Context` and `context.Context` would not go amiss.

**Comment by ChrisJBurns** [comment]
@evantorrie Yes that is understandable. Thanks for all your help!
