### ISSUE TITLE
Point release of go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.35.0 needed

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#3513]
In order to unblock the Kubernetes project, the fix from https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2983 needs to be back-ported to v0.35.0 for the go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp package.

### Proposal

1. Create a branch from the v0.35.1 release
2. Cherry-pick the fix from #2983 to that branch
3. Tag the branch with `instrumentation/net/http/otelhttp/v0.35.1`

**Comment by dashpole** [comment]
The initial bug from upstream: https://github.com/kubernetes/kubernetes/issues/113791.  Because of that, the tracing feature in k8s is not useable until we get this fix.

I tried to update the otelhttp version here: https://github.com/kubernetes/kubernetes/pull/115208 but discovered that it was blocked by https://github.com/kubernetes/kubernetes/issues/113366, which looks like it will take a while to resolve.

**Comment by MrAlias** [comment]
I created the [`release-otelhttp-v0.35.1`](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/release-otelhttp-v0.35.1) for this.

**Comment by MrAlias** [comment]
Point release complete: https://github.com/open-telemetry/opentelemetry-go-contrib/tree/instrumentation/net/http/otelhttp/v0.35.1
