### ISSUE TITLE
Upgrade to v0.13.0 of go.opentelemetry.io/otel 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-go-contrib#389]
The new version moved/renamed several packages. Therefore we cannot upgrade to otel v0.13.0 without go-contrib also upgrading

**Comment by Aneurysm9** [comment]
Upgrading contrib is a standard part of our release process and typically follows a day behind.  I've started on this process, but the propagator changes this time around are less amenable to `s///g` so it may take slightly longer.

**Comment by codeboten** [comment]
Hey @Aneurysm9, I wasn't sure if it was part of the process or not so thanks for clarifying!

**Comment by Aneurysm9** [comment]
No worries! I'd love to have a process whereby we could release the main repo and contrib simultaneously, but I'm not sure I see a great way to it since we need to be able to update the `go.mod` files in contrib to point to the new release tag.  Once we hit 1.0 this will (hopefully) become a non-issue as we'll stop breaking things with every release! :)
