### ISSUE TITLE
otelgrpc: Add metrics tests for ServerStreamInterceptors

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go-contrib#4323]
### Problem Statement

There are two problems discovered in #4322:
1. There are no tests around the metrics produced by a ServerStreamInteceptor
2. Under test, ServerStreamInteceptors don't have `peerInfo` within the call made.  This means that peer info will not show in tests, but does show in actual use.

### Proposed Solution

Write a test similar to [checkUnaryServerRecords](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/bf86b26a1d265ad04a07ae2abadcd08e9d18e174/instrumentation/google.golang.org/grpc/otelgrpc/test/grpc_test.go#L601) to assert that the produced metrics match

Change the test such that it does have peerInfo within it's context

**Comment by fatsheep9146** [comment]
@pellard @MadVikingGod 
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/b39f96ec9d9f8510c1873194d872b028efada5a1/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L449-L499
I found that the `ServerStreamInterceptors` do not produce metric for now, only ServerUnaryInterceptors support, do we need add metrics support for `ServerStreamInterceptors` and then add test for it? Or should we directly support metrics in `StatsHandler`, since interceptors will be deprecated in some day.

**Comment by pellared** [comment]
I think that we wanted to add tests for metrics emitted by server interceptors.

I propose to leave implementation and just add assertions for metrics emitted by the interceptors. You can consider adding an assertion showing that `ServerStreamInterceptors` does NOT produce any metrics 😉

I think adding support for metrics in `ServerStreamInterceptors` is a waste of our time. I would rather work towards making `StatsHandler` as good as possible.

@MadVikingGod do you agree?

**Comment by MadVikingGod** [comment]
I was under the impression that the different Interceptors were being deprecated, if that's the case, then I don't think any functionality should be added.

I think there should be some testing around what metrics (if any) are put out by both the stat's handler and the interceptors, and peer Attributes must be part of that dataset.

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4318
