### ISSUE TITLE
Remove dependency on package intended for internal testing only `google.golang.org/grpc/interop`

### ISSUE THREAD

**Issue by arvindbr8** [open-telemetry/opentelemetry-go-contrib#4896]
### Description

`google.golang.org/grpc/interop` [package](github.com/grpc/grpc-go/tree/d41b01db97ca2e3627b2c9949fffe8f152a4255d/interop) was meant for internal usage in the gRPC repo and never intended to be imported by other repos. Our weekly import is blocked when we noticed a breaking test in otelgrpc in google3 due a recent change to the package (https://github.com/grpc/grpc-go/pull/6827). 

### Expected behavior

I think the right way to approach this would be to fork `google.golang.org/grpc/interop` package to this repo and make use of that instead in tests. 

Please advice.

**Comment by MrAlias** [comment]
I think we could approach this in two phases.

1. It sounds like there was API changes to the `interop` package that are breaking. We are likely going make a patch release in `otel` today or within the next few days, we could quickly patch the use of `iterop` to use the new API and upgrade.
2. Long-term forking, or developing our own more fitting replacement sounds like a good plan.

@arvindbr8 out of curiosity for other projects of mine and for future reference, it seems like you are involved with the Go gRPC package, what is the long term plan there? There are [522](https://pkg.go.dev/google.golang.org/grpc/interop?tab=importedby) imports of that package, most from outside the gRPC project. Are you planning to deprecate it and move it to an `internal` package. Or just document that is shouldn't be used?

**Comment by dashpole** [comment]
Chatted with @arvindbr8 offline, as we have a resolution for the google-internal motivation for this issue, regardless of the path taken in OSS.  We can still do phase 1 from https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4896#issuecomment-1932677366, but it isn't required to unblock us. I would definitely be hesitant to pin to an unreleased version if the breaking changes to `interop` haven't been released yet.

From our discussion, it sounds like the `interop` package may predate `internal` directories in Go, which is why it isn't restricted.
