### ISSUE TITLE
Make `otelhttp` produce old, new and duplicate Client Trace Attributes

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go-contrib#5332]
Make `instrumentation/net/http/otelhttp` produce Client Traces following the migration plan #5132.

A user should be able to produce Traces from the `Transport` in the current semconv (default), the latest semconv (1.26.0), and a duplicate form based on the Environment variable `OTEL_HTTP_CLIENT_COMPATIBILITY_MODE`

- [x] Produce Old Client Attributes
- ~Produce Duplicate Client Attributes~
- [x] Produce New Client Attributes
- [x] Add a changelog entry

**Comment by VinozzZ** [comment]
I would like to work on the remaining task for this issue

**Comment by VinozzZ** [comment]
Implementation Plan:
- Create a `newHTTPClient` that returns attributes from [semconv v1.26.0](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#http-client)
- the `newHTTPClient` should implement `RequestTraceAttrs`, `ResponseTraceAttrs`, and `Status` methods
- Add tests to check `newHTTPClient` is returning correct attributes 
- Add logic to check for environment variable `OTEL_HTTP_CLIENT_COMPATIBILITY_MODE` in `HTTPClient` to also return attributes from `newHTTPClient` if the env is set to `http/dup`. Otherwise, only return attributes from the `oldHTTPClient`

**Comment by MrAlias** [comment]
Done.
