### ISSUE TITLE
`otelgrpc` possibly reporting status code in incorrect format

### ISSUE THREAD

**Issue by achew22** [open-telemetry/opentelemetry-go-contrib#5910]
### Description

Right now, `otelgrpc` is reporting `rpc.grpc.status_code` as defined in [`semconv`](https://pkg.go.dev/go.opentelemetry.io/otel/semconv/v1.17.0) as an integer. It's entirely possible I'm holding it wrong though. Would love a pointer if that's the case.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/instrumentation/google.golang.org/grpc/otelgrpc/v0.53.0/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go#L199-L201

As I read [the spec](https://opentelemetry.io/docs/specs/otel/common/attribute-type-mapping/#enumerations) on enumerations, they should be converted to the string type before being uploaded.

> Values, which belong to a limited enumerated set (e.g. a Java [enum](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html)), SHOULD be converted to AnyValue’s [string_value](https://github.com/open-telemetry/opentelemetry-proto/blob/38b5b9b6e5257c6500a843f7fdacf89dd95833e8/opentelemetry/proto/common/v1/common.proto#L31) field with the value of the string set to the symbolic name of the enumeration.

### Environment

- OS: Linux
- Architecture: x86-64
- Go Version: 1.21
- `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.49.0`

### Steps To Reproduce

1. Install the `otelgrpc` package in your gRPC server
2. Run the service
3. See integers in the metrics for the 

### Expected behavior

I would expect these to be strings describing the gRPC status codes. Could be wrong in my interpretation of the spec.

**Comment by dmathieu** [comment]
This isn't the proper spec to look at.
> The mapping is needed when OpenTelemetry needs to convert a value produced outside OpenTelemetry into a value that can be exported using an OTLP exporter

We are not producing a value from outside OpenTelemetry into a value that can be used by OTLP. We are within OpenTelemetry, and are producing data for any exporter, not specifically OTLP.
This spec would apply in a bridge that would allow transforming data from one format into OTLP.

What applies here is semantic conventions.
https://github.com/open-telemetry/semantic-conventions/blob/f79fe6b61438bfa0804df9c254c402fd0d71f42a/docs/rpc/grpc.md#grpc-attributes

And the gRPC status code is indeed an integer (which makes sense, since that's the original data type).
