### ISSUE TITLE
Adds support for B3 single and multi

### ISSUE THREAD

**Issue by jcchavezs** [open-telemetry/opentelemetry-go-contrib#732]
## Background

B3 has support for two encoding of the trace context: B3 single and multiple however it can happen that for easy migration of propagation or just because of support (e.g. async where b3 single is defacto to sync where b3 multi is very common) we can have both headers. Some examples are https://github.com/openzipkin/zipkin-go/blob/815bc64e1a6031d5a51c88b07092d34c20aaeb61/propagation/b3/http.go#L33 or https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Propagation/B3.php#L101 hence we should support both encodings in this repository. Otherwise, it will be really hard for people to slowly move into single B3.

## Proposed Solution

We add another encoding type in https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/b3/b3_propagator.go#L71

### Prior Art

See previous links

Ping @anuraaga @XSAM @Aneurysm9

**Comment by Aneurysm9** [comment]
Can this be achieved with a composite propagator composing two B3 propagators, one for each of the single- and multi-header encodings?  If it's a transitional usage and we're already able to account for it with existing implementations I'm not sure adding more moving parts is the right approach.

**Comment by jcchavezs** [comment]
I think that is a bit overkill, this is a problem specifically for the duality of B3 so I think it deserves a custom approach.

**Comment by Aneurysm9** [comment]
Been a while since I read the B3 propagator code, but it looks like using a composite propagator isn't even necessary.  The `Encoding` constants are [defined as bitmask values](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/b3/b3_propagator.go#L74) and the propagator will inject using [any](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/b3/b3_propagator.go#L107) [supported](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/b3/b3_propagator.go#L126) `Encoding`.  Constructing a `B3` propagator with an appropriate `InjectEncoding` should be sufficient here:

```go
prop := B3{InjectEncoding: B3MultipleHeader | B3SingleHeader}
```

[This test](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/b3/b3_integration_test.go#L166-L176) and [these test cases](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/b3/b3_data_test.go#L870-L980) should ensure that property.

**Comment by MrAlias** [comment]
> Constructing a `B3` propagator with an appropriate `InjectEncoding` should be sufficient here:
> 
> ```go
> prop := B3{InjectEncoding: B3MultipleHeader | B3SingleHeader}
> ```

Correct, this is already supported.
