### ISSUE TITLE
Use singular form for directory names

### ISSUE THREAD

**Issue by rhcarvalho** [open-telemetry/opentelemetry-go-contrib#810]
It is common practice in Go to name package path components in singular, so

- `exporter/metric/...`
- `propagator`
- `detector`
- `instrumentation` (currently already in singular form)

Right now of the 4 areas of this repo, one is already in singular form and the other 3 are plural.

Other Go repos in OpenTelemetry do follow the practice of using singular, for example the [Collector](https://github.com/open-telemetry/opentelemetry-collector) and [Collector-Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib).

Opening this issue to discuss renaming `exporters/`, `propagators/` and `detectors/` to the singular form before GA.

**Comment by MrAlias** [comment]
Changing these names needs to be done with a lot of caution. It will change the module/package names meaning there will be discoverability issues in the future when users find the old deadend modules/packages and think they are the current ones.

There are examples of plurals in other Go projects including the standard library: `bytes`, `errors`, `strings`. We should be sure we are making the change for an agreed upon reason instead of a preference here.

**Comment by MrAlias** [comment]
Thanks for the suggestion. At this point the stability of the packages this provides outweighs the desire to use more common singular names in the package. Closing.
